### PR TITLE
Copyrights

### PR DESCRIPTION
**Pull request by spg**
See #186

### CODE REVIEW

**Comment by meriouma** [comment]
LGTM. But shouldn't we just put 2015 for new files (except for the files where it was still the Julien Dramaix's copyright)? I thought it was always the inception year?

**Comment by spg** [comment]
@meriouma yep you're right, but I lack the tools to do this easily and automatically. Scanning for new files by hand and manually modifying the copyright dates is tedious.

**Comment by meriouma** [comment]
Yeah sure, no worries!

**Comment by jDramaix** [comment]
LGTM

**Comment by jDramaix** [comment]
@meriouma Are the integration tests run by team-city ?

**Comment by christiangoudreau** [comment]
LGTM

**Comment by spg** [comment]
@jDramaix yes they are: http://teamcity.arcbees.com/project.html?projectId=GWTChosen&tab=projectOverview

**Pull request merged**
