### PR TITLE
Fix Enabled/Disabled problem

### PR DESCRIPTION
**Pull request by spg**
@jDramaix This is a fix for https://github.com/ArcBees/gwtchosen/pull/198, which apparently didn't work.

### CODE REVIEW

**Comment by christiangoudreau** [comment]
LGTM

**Comment by meriouma** [comment]
LGTM

**Comment by jDramaix** [comment]
LGTM

**Comment by jDramaix** [comment]
The #198 works but thisis a better solution. Thanks

**Pull request merged**
