### PR TITLE
gwtchosen-142 Tab index is not reset if change handler triggers further ...

### PR DESCRIPTION
**Pull request by cplaetzinger**
Possible fix for #142

### CODE REVIEW

**Comment by christiangoudreau** [comment]
@jDramaix

**Comment by jDramaix** [comment]
@christiangoudreau  ?

**Comment by christiangoudreau** [comment]
What do we do with this? @jDramaix

**Comment by jDramaix** [comment]
I'm against this change and waiting more info from @cplaetzinger .

**Comment by cplaetzinger** [comment]
What we do can be summarized as follows:
* Listen for changes on the ChosenListBox by adding a ChangeHandler
* Once the handler gets triggered the event is forwarded to our own event handling
* At the end this leads to a communication with the server part of our GWT application. During event handling/server communication the application displays a spinning activity indicator (like spin.js) using an overlay window.
* The result received from the server is used to update the ui, e.g add components, remove components, change some attributes on existing components. But it does not build an entire new windows. Thus the original components still exists.

**Comment by olafleur** [comment]
Last commit was more than 6 months ago. Closing. Feel free to reopen a pull request as needed.

**Pull request closed without merging**
