### PR TITLE
Check the last version of GWTChosen

### PR DESCRIPTION
**Pull request by olafleur**

### CODE REVIEW

**Comment by meriouma** [comment]
Any way do disable it like in GWTP?

**Comment by olafleur** [comment]
<set-configuration-property name="chosenVerifyNewerVersion" value="false"/>

**Comment by meriouma** [comment]
In fact having the same property to skip the check could be a good idea. One property to disable checks for all our libs

**Comment by olafleur** [comment]
Done.

**Comment by meriouma** [comment]
LGTM

**Comment by olafleur** [comment]
When applied on a real project, the current version is shown as null.

**Comment by olafleur** [comment]
@jasonlemay

**Pull request merged**
